#!/bin/bash

# Update package list and install pip3
sudo apt update -y
sudo apt install -y python3-pip

# Install virtualenv using pip3
sudo pip3 install virtualenv

# Change directory to the app location
cd /home/ubuntu/app

# Create a virtual environment
virtualenv environment

# Activate the virtual environment
source environment/bin/activate

# Install dependencies from requirements.txt
pip3 install -r requirements.txt
